name: Build unofficial-sigs

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build unofficial-sigs
        run: |
          make unofficial-sigs
